from snakemake.io import touch, directory, temp, expand
from scripts.utils import read_genome_paths, read_genome_names, get_path_using_name

# read paths & names
paths = read_genome_paths(config.get("samples_table", []))
names = read_genome_names(config.get("samples_table", []))

rule all:
    input:
        expand("results/final/{name}_{path}.done", name=names, path=paths)


rule rename_scaffolds:
    input: lambda  wildcards: get_path_using_name(name=wildcards.name, file_path=config.get("samples_table", []))
    output: "assemblies/{name}_ref.fasta"
    shell: "awk '/^>/{print \">sc\" ++i; next}{print}' < {input} > {output}"

rule repeat_modeler:
    input:
        "assemblies/{genome}.fna"
    output:
        "results/repeatmodeler/{genome}/consesni.fa"
    shell:
        ""

rule final:
    input:
        "assemblies/{name}/ref.fa"
    output:
        "results/final/{name}_{path}.done"
    shell:
        "touch {output}"